### ISSUE TITLE
Убрать лишние параметры и добавить новые

### ISSUE THREAD

**Issue by sertokinson** [MrBlackD/ScriptMaker#33]
Убрать описание у динамического параметра(description), required, keepinworkflow
Создать сущность обертку DynamicParamExtended и добавить required, keepinworkflow (обязательные)
Добавить тип (type - string)

**Comment by MrBlackD** [comment]
Еще для расщиренной сущности нужно необязательное поле defaultValue.

**Comment by MrBlackD** [comment]
Done
